CREATE sequence BRANCH_TYPES_SEQ;
CREATE sequence CONTAINER_SEQ;
CREATE sequence DISCIPLINES_SEQ;
CREATE sequence GRADESJOURNAL_SEQ;
CREATE sequence LESSONSPLAN_SEQ;
CREATE sequence MESSAGES_SEQ;
CREATE sequence PERSON_SEQ;
