CREATE sequence L3G3_BRANCH_TYPE_SEQ;
CREATE sequence L3G3_CONTAINER_SEQ;
CREATE sequence L3G3_DISCIPLINE_SEQ;
CREATE sequence L3G3_GRADESJOURNAL_SEQ;
CREATE sequence L3G3_LESSONSPLAN_SEQ;
CREATE sequence L3G3_MESSAGE_SEQ;
CREATE sequence L3G3_PERSON_SEQ;
CREATE sequence L3G3_ROLE_SEQ;
